-- core/db/schema.sql
-- ==================
-- CCSS-Scan Framework — database schema (SQLite compatible)

CREATE TABLE IF NOT EXISTS targets (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    name             TEXT    NOT NULL UNIQUE,
    display_name     TEXT    NOT NULL,
    version          TEXT    NOT NULL,
    benchmark_source TEXT    NOT NULL,
    created_at       TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at       TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- A host is an Operating System instance scans are attributed to (e.g.
-- --host web01). Optional: scans with no host tag simply never appear in
-- any Operating-System-level rollup.
--
-- IDENTITY (v2). `uuid` is the host's identity and never changes once
-- assigned at first registration. Everything an operator sees — label,
-- hostname, ip_address — is a mutable ATTRIBUTE, because all of them do
-- change in practice: machines get renamed, DHCP hands out a different
-- address, a VM is cloned. Keying identity on any of them would silently
-- split one host's history in two, or worse, merge two hosts into one.
--
-- `label` stays UNIQUE: it is the operator-facing handle that `--host web01`
-- resolves through, and the uniqueness is what makes that resolution
-- unambiguous.
CREATE TABLE IF NOT EXISTS hosts (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid         TEXT    NOT NULL UNIQUE,
    label        TEXT    NOT NULL UNIQUE,
    hostname     TEXT,
    ip_address   TEXT,
    os_family    TEXT,
    os_version   TEXT,
    kernel       TEXT,
    -- Wall-clock of the last successful attribute collection. NULL means the
    -- host was registered by label alone and never inspected — a distinct
    -- state from "inspected and found empty".
    last_seen_at TEXT,
    created_at   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS misconfigurations (
    id               TEXT    PRIMARY KEY,
    target_id        INTEGER NOT NULL REFERENCES targets(id) ON DELETE CASCADE,
    target_name      TEXT    NOT NULL,
    directive        TEXT    NOT NULL,
    bad_value        TEXT    NOT NULL,
    good_value       TEXT    NOT NULL DEFAULT '',
    av               TEXT    NOT NULL DEFAULT 'N',
    au               TEXT    NOT NULL DEFAULT 'N',
    ac               TEXT    NOT NULL,
    c                TEXT    NOT NULL,
    i                TEXT    NOT NULL,
    a                TEXT    NOT NULL,
    base_score       REAL    NOT NULL DEFAULT 0.0,
    temporal_score   REAL    NOT NULL DEFAULT 0.0,
    gel              TEXT    NOT NULL DEFAULT 'ND',
    grl              TEXT    NOT NULL DEFAULT 'ND',
    cves             TEXT    NOT NULL DEFAULT '[]',
    cce_id           TEXT    NOT NULL DEFAULT '',
    cis_section      TEXT    NOT NULL DEFAULT '',
    justification    TEXT    NOT NULL DEFAULT '',
    recommendation   TEXT    NOT NULL DEFAULT '',

    -- Absence detection fields (Phase 1 extension).
    -- rule_type = 'value' (lookup by bad_value) | 'absence' (directive missing)
    -- required_when = 'always' | 'if_directive:<name>' (conditional firing)
    -- expected_value_prefix: for multi-instance directives (e.g. add_header),
    --   the value prefix that must be present; '' means pure directive absence.
    rule_type             TEXT    NOT NULL DEFAULT 'value',
    required_when         TEXT    NOT NULL DEFAULT 'always',
    expected_value_prefix TEXT    NOT NULL DEFAULT '',

    -- Stage 3: rich narrative generated by LLM at build time.
    -- JSON object with fields:
    --   description: str
    --   potential_impact: list[str]
    --   exploitation_scenario: {prerequisites: list[str], example: str, result: str}
    --   metric_justifications: {ac, c, i, a, gel, grl: str}
    --   (av and au justifications are generated at runtime by the rule engine)
    narrative        TEXT    NOT NULL DEFAULT '{}',

    -- Self-consistency agreement rate from the LLM build pipeline (Chapter 4 /
    -- DISSERTACAO_REFERENCIA.md §4.7.2): fraction of the k sampled LLM calls
    -- that agreed with the majority vote on the least-consensual metric.
    -- 1.0 for curated/no-LLM rules and for a single unanimous sample; 0.0 for
    -- the conservative fallback (all k samples failed to parse/validate).
    confidence       REAL    NOT NULL DEFAULT 1.0,

    created_at       TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at       TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (target_name, directive, bad_value, expected_value_prefix)
);

CREATE INDEX IF NOT EXISTS idx_misconf_lookup
    ON misconfigurations (target_name, directive, bad_value);

CREATE INDEX IF NOT EXISTS idx_misconf_target
    ON misconfigurations (target_name);

-- Migration helper: add narrative column to existing databases
-- (SQLite ignores ADD COLUMN if it already exists via IF NOT EXISTS workaround)
-- The database.py migration method handles this at startup.

CREATE TABLE IF NOT EXISTS attack_chains (
    id                   INTEGER PRIMARY KEY AUTOINCREMENT,
    target_id            INTEGER NOT NULL REFERENCES targets(id) ON DELETE CASCADE,
    target_name          TEXT    NOT NULL,
    chain_id             TEXT    NOT NULL,
    misconfig_directives TEXT    NOT NULL DEFAULT '[]',
    amplification        REAL    NOT NULL DEFAULT 1.0,
    justification        TEXT    NOT NULL DEFAULT '',
    cross_target         INTEGER NOT NULL DEFAULT 0,
    created_at           TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (target_name, chain_id)
);

CREATE INDEX IF NOT EXISTS idx_chains_target
    ON attack_chains (target_name);

CREATE TABLE IF NOT EXISTS scan_results (
    id                      TEXT    PRIMARY KEY,
    target_name             TEXT    NOT NULL,
    input_path              TEXT    NOT NULL,
    input_hash              TEXT    NOT NULL,
    profile_av              TEXT    NOT NULL,
    profile_au              TEXT    NOT NULL,
    global_base_score       REAL    NOT NULL DEFAULT 0.0,
    global_temporal_score   REAL    NOT NULL DEFAULT 0.0,
    severity                TEXT    NOT NULL DEFAULT 'None',
    total_directives        INTEGER NOT NULL DEFAULT 0,
    total_issues            INTEGER NOT NULL DEFAULT 0,
    total_chains            INTEGER NOT NULL DEFAULT 0,
    issues_json             TEXT    NOT NULL DEFAULT '[]',
    chains_json             TEXT    NOT NULL DEFAULT '[]',
    -- Manifesto de reprodutibilidade (core/manifest.py): versão do código e
    -- sha256 do conteúdo da base que produziram estes scores. Sem ele gravado,
    -- um resultado relido da base não se pode auditar — e é essa auditoria a
    -- afirmação que a metodologia faz.
    manifest_json           TEXT    NOT NULL DEFAULT '{}',
    timestamp               TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_scan_results_target
    ON scan_results (target_name);

CREATE INDEX IF NOT EXISTS idx_scan_results_hash
    ON scan_results (input_hash);

-- One row per `caspar watch` session, upserted on every poll tick (not just on
-- content change, unlike scan_results) — this is what lets the dashboard tell
-- "still running, nothing changed" apart from "process died". Deliberately
-- separate from scan_results: it is overwritten in place, never appended to.
CREATE TABLE IF NOT EXISTS watch_heartbeats (
    watch_session   TEXT    PRIMARY KEY,
    last_seen       TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- Pre-fetched version exploitability (F1). Populated at build time by
-- `ccss fetch-exploits` (NVD + Exploit-DB), read locally at runtime so the
-- scan path stays offline and deterministic. exploits_json holds the resolved
-- Exploit-DB records so the runtime never shells out to searchsploit either.
CREATE TABLE IF NOT EXISTS version_exploits (
    product     TEXT    NOT NULL,
    version     TEXT    NOT NULL,
    cve_count   INTEGER NOT NULL DEFAULT 0,
    kev_count   INTEGER NOT NULL DEFAULT 0,
    max_cvss    REAL    NOT NULL DEFAULT 0.0,
    cve_ids     TEXT    NOT NULL DEFAULT '[]',
    exploits    TEXT    NOT NULL DEFAULT '[]',
    fetched_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    PRIMARY KEY (product, version)
);

-- Background jobs (build/plugin_add/...) started from the REST API. A single-
-- process app, so job state lives here rather than Redis/Celery — a thread
-- runs the job, this table is how the poller (and a server restart) observes
-- it. job_logs is append-only so the poller can ask for "lines after seq N".
CREATE TABLE IF NOT EXISTS jobs (
    id           TEXT    PRIMARY KEY,
    kind         TEXT    NOT NULL,
    status       TEXT    NOT NULL DEFAULT 'queued',
    params_json  TEXT    NOT NULL DEFAULT '{}',
    result_json  TEXT,
    error        TEXT,
    created_at   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    started_at   TEXT,
    finished_at  TEXT
);

CREATE TABLE IF NOT EXISTS job_logs (
    job_id  TEXT    NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    seq     INTEGER NOT NULL,
    ts      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    line    TEXT    NOT NULL,
    PRIMARY KEY (job_id, seq)
);
