import type {
  Chain,
  Finding,
  Posture,
  Target,
  WatchEvent,
  WatchSession,
} from "./types";

export const ASSESSED_AT = "2026-08-12T14:32:00Z";

export const posture: Posture = {
  overall: {
    score: 8.5,
    severity: "High",
    delta: -0.4,
    driver: {
      kind: "finding",
      dimension: "configuration",
      label: "ServerTokens = Full",
      finding_id: "3f2b1c9a",
    },
  },
  coverage: { dimensions_total: 6, dimensions_assessed: 3, percent: 50 },
  dimensions: [
    {
      id: "configuration",
      label: "Configuration",
      status: "assessed",
      score: 8.5,
      severity: "High",
      weight: 0.35,
      findings_count: 10,
      critical_count: 2,
      delta: -0.4,
      assessed_at: ASSESSED_AT,
      description:
        "Directive-level review of service configuration files against hardening benchmarks.",
      would_measure: [],
      trend: [
        { t: "06 Aug", score: 9.1 },
        { t: "07 Aug", score: 9.0 },
        { t: "08 Aug", score: 8.8 },
        { t: "09 Aug", score: 8.9 },
        { t: "10 Aug", score: 8.7 },
        { t: "11 Aug", score: 8.9 },
        { t: "12 Aug", score: 8.5 },
      ],
    },
    {
      id: "permissions",
      label: "Identity & Permissions",
      status: "assessed",
      score: 6.2,
      severity: "Medium",
      weight: 0.3,
      findings_count: 6,
      critical_count: 0,
      delta: 0.0,
      assessed_at: ASSESSED_AT,
      description:
        "Filesystem ownership, modes and privilege-escalation policy across assessed hosts.",
      would_measure: [],
      trend: [
        { t: "06 Aug", score: 6.2 },
        { t: "07 Aug", score: 6.2 },
        { t: "08 Aug", score: 6.4 },
        { t: "09 Aug", score: 6.3 },
        { t: "10 Aug", score: 6.2 },
        { t: "11 Aug", score: 6.2 },
        { t: "12 Aug", score: 6.2 },
      ],
    },
    {
      id: "exposure",
      label: "Network Exposure",
      status: "assessed",
      score: 7.4,
      severity: "High",
      weight: 0.35,
      findings_count: 8,
      critical_count: 2,
      delta: 1.2,
      assessed_at: ASSESSED_AT,
      description:
        "Listening sockets, bound interfaces and reachability of services beyond localhost.",
      would_measure: [],
      trend: [
        { t: "06 Aug", score: 6.1 },
        { t: "07 Aug", score: 6.2 },
        { t: "08 Aug", score: 6.2 },
        { t: "09 Aug", score: 6.5 },
        { t: "10 Aug", score: 7.0 },
        { t: "11 Aug", score: 7.1 },
        { t: "12 Aug", score: 7.4 },
      ],
    },
    {
      id: "secrets",
      label: "Secrets",
      status: "not_assessed",
      score: null,
      severity: null,
      weight: null,
      findings_count: null,
      critical_count: null,
      delta: null,
      assessed_at: null,
      description: "Never executed on this engagement — no collector granted access.",
      would_measure: [
        "Credentials committed to configuration files and environment blocks",
        "Private keys and certificates with weak protection",
        "Token lifetime and rotation policy",
      ],
    },
    {
      id: "patch",
      label: "Software & Patch Intelligence",
      status: "not_assessed",
      score: null,
      severity: null,
      weight: null,
      findings_count: null,
      critical_count: null,
      delta: null,
      assessed_at: null,
      description: "Never executed — the package inventory collector has not been enabled.",
      would_measure: [
        "Installed package versions against vendor advisories",
        "Known-exploited vulnerabilities present on assessed hosts",
        "Distance from the fixed version for each affected package",
      ],
    },
    {
      id: "hardening",
      label: "Platform Hardening",
      status: "not_assessed",
      score: null,
      severity: null,
      weight: null,
      findings_count: null,
      critical_count: null,
      delta: null,
      assessed_at: null,
      description: "Never executed — requires a privileged agent on each host.",
      would_measure: [
        "Kernel parameters and mandatory access control state",
        "Boot integrity and module signing",
        "Audit subsystem and logging configuration",
      ],
    },
  ],
  chains: { active_count: 6, highest_score: 9.5, exceeds_overall: true },
  totals: {
    targets_assessed: 12,
    rules_evaluated: 514,
    findings_open: 24,
    critical_findings: 4,
    related_cves: 6,
  },
  scoring_model: { version: "2.0", aggregation: "weighted", missing_dimension_policy: "excluded" },
  manifest: { cvm_version: "2.0.0", db_sha256: "f595efe56da0", scoring_model_version: "2.0" },
  assessed_at: ASSESSED_AT,
};

export const overallTrend: { t: string; score: number; model: string }[] = [
  { t: "29 Jul", score: 7.9, model: "1.9" },
  { t: "31 Jul", score: 8.1, model: "1.9" },
  { t: "02 Aug", score: 8.0, model: "1.9" },
  { t: "04 Aug", score: 8.6, model: "2.0" },
  { t: "06 Aug", score: 8.8, model: "2.0" },
  { t: "08 Aug", score: 9.0, model: "2.0" },
  { t: "10 Aug", score: 8.9, model: "2.0" },
  { t: "12 Aug", score: 8.5, model: "2.0" },
];

export const modelBoundary = { t: "04 Aug", from: "1.9", to: "2.0" };

export const findings: Finding[] = [
  {
    id: "3f2b1c9a",
    dimension: "configuration",
    target: "apache-httpd",
    target_label: "Apache HTTPD",
    icon_key: "apache",
    identifier: "ServerTokens",
    observed_value: "Full",
    expected_value: "Prod",
    score: 8.5,
    severity: "High",
    title: "Server version disclosed in HTTP responses",
    impact:
      "Reveals the exact Apache version to any client, letting an attacker match known exploits without probing.",
    recommendation: "Set ServerTokens to Prod in the main configuration.",
    evidence: {
      kind: "config_file",
      location: "/etc/apache2/apache2.conf",
      line: 142,
      snippet: "ServerTokens Full",
    },
    cves: ["CVE-2023-25690"],
    in_chains: ["chain-rce-escalation-03"],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "9d1f4e2c",
    dimension: "exposure",
    target: "redis",
    target_label: "Redis",
    icon_key: "redis",
    identifier: "tcp/0.0.0.0:6379",
    observed_value: "0.0.0.0 (all interfaces)",
    expected_value: "127.0.0.1",
    score: 9.4,
    severity: "Critical",
    title: "Redis listening on all network interfaces without authentication",
    impact:
      "Any host that can route to this machine can read and write the entire dataset, and Redis commands allow writing files to disk.",
    recommendation: "Bind Redis to 127.0.0.1, or restrict access at the firewall and enable requirepass.",
    evidence: {
      kind: "listening_socket",
      location: "tcp/0.0.0.0:6379",
      process: "redis-server",
      pid: 1412,
    },
    cves: [],
    in_chains: ["chain-data-exfiltration-01"],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "5a8c3b7d",
    dimension: "permissions",
    target: "ubuntu",
    target_label: "Ubuntu",
    icon_key: "ubuntu",
    identifier: "/etc/shadow",
    observed_value: "0644 root:root",
    expected_value: "0640 root:shadow",
    score: 7.8,
    severity: "High",
    title: "Password hash file readable by all local users",
    impact:
      "Any local account can read every password hash on the system and attempt offline cracking.",
    recommendation: "Run: chmod 0640 /etc/shadow && chown root:shadow /etc/shadow",
    evidence: {
      kind: "file_metadata",
      location: "/etc/shadow",
      mode: "0644",
      owner: "root",
      group: "root",
    },
    cves: [],
    in_chains: ["chain-local-escalation-02"],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "7c4e2a1b",
    dimension: "exposure",
    target: "apache-httpd",
    target_label: "Apache HTTPD",
    icon_key: "apache",
    identifier: "tcp/0.0.0.0:80",
    observed_value: "0.0.0.0:80 reachable off-host",
    expected_value: "reverse proxy only",
    score: 5.2,
    severity: "Medium",
    title: "HTTP service answers on every interface",
    impact:
      "The service is reachable from any network the host is attached to, widening the population of possible attackers.",
    recommendation: "Bind the listener to the internal interface or place it behind the ingress proxy.",
    evidence: {
      kind: "listening_socket",
      location: "tcp/0.0.0.0:80",
      process: "apache2",
      pid: 908,
    },
    cves: [],
    in_chains: ["chain-rce-escalation-03"],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "b4e91d70",
    dimension: "permissions",
    target: "apache-httpd",
    target_label: "Apache HTTPD",
    icon_key: "apache",
    identifier: "/var/www:mode",
    observed_value: "0775 www-data:www-data",
    expected_value: "0755 root:www-data",
    score: 6.9,
    severity: "Medium",
    title: "Web root writable by the service account",
    impact:
      "Code execution in the web server process becomes persistent: the attacker can drop a web shell into the document root.",
    recommendation: "Run: chown root:www-data /var/www && chmod 0755 /var/www",
    evidence: {
      kind: "file_metadata",
      location: "/var/www",
      mode: "0775",
      owner: "www-data",
      group: "www-data",
    },
    cves: [],
    in_chains: ["chain-rce-escalation-03"],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "c07a5f31",
    dimension: "permissions",
    target: "ubuntu",
    target_label: "Ubuntu",
    icon_key: "ubuntu",
    identifier: "sudoers:NOPASSWD",
    observed_value: "%deploy ALL=(ALL) NOPASSWD: ALL",
    expected_value: "password required",
    score: 6.5,
    severity: "Medium",
    title: "Sudo policy grants full privileges without re-authentication",
    impact:
      "Any compromise of a deploy account becomes root immediately, with no password prompt to slow the attacker down.",
    recommendation: "Remove NOPASSWD from the deploy group entry in /etc/sudoers.d/deploy.",
    evidence: {
      kind: "config_file",
      location: "/etc/sudoers.d/deploy",
      line: 3,
      snippet: "%deploy ALL=(ALL) NOPASSWD: ALL",
    },
    cves: [],
    in_chains: ["chain-local-escalation-02"],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "1e5d8a44",
    dimension: "configuration",
    target: "openssh",
    target_label: "SSH",
    icon_key: "ssh",
    identifier: "PermitRootLogin",
    observed_value: "yes",
    expected_value: "prohibit-password",
    score: 9.1,
    severity: "Critical",
    title: "Direct root login permitted over SSH",
    impact:
      "A single credential guess against a well-known username yields full administrative access with no lateral step required.",
    recommendation: "Set PermitRootLogin prohibit-password and reload sshd.",
    evidence: {
      kind: "config_file",
      location: "/etc/ssh/sshd_config",
      line: 34,
      snippet: "PermitRootLogin yes",
    },
    cves: ["CVE-2016-0777"],
    in_chains: ["chain-ssh-takeover-04"],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "2b77c0e9",
    dimension: "configuration",
    target: "openssh",
    target_label: "SSH",
    icon_key: "ssh",
    identifier: "PasswordAuthentication",
    observed_value: "yes",
    expected_value: "no",
    score: 6.8,
    severity: "Medium",
    title: "Password authentication enabled on SSH",
    impact: "Exposes the service to credential stuffing and brute force from the open internet.",
    recommendation: "Set PasswordAuthentication no and enforce key-based access.",
    evidence: {
      kind: "config_file",
      location: "/etc/ssh/sshd_config",
      line: 58,
      snippet: "PasswordAuthentication yes",
    },
    cves: [],
    in_chains: ["chain-ssh-takeover-04"],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "88ac21fd",
    dimension: "exposure",
    target: "openssh",
    target_label: "SSH",
    icon_key: "ssh",
    identifier: "tcp/0.0.0.0:22",
    observed_value: "0.0.0.0:22 reachable from WAN",
    expected_value: "bastion range only",
    score: 7.6,
    severity: "High",
    title: "SSH reachable from any source address",
    impact:
      "Administrative access is exposed to the entire internet rather than a restricted management range.",
    recommendation: "Restrict inbound 22/tcp to the bastion CIDR at the security group.",
    evidence: { kind: "listening_socket", location: "tcp/0.0.0.0:22", process: "sshd", pid: 731 },
    cves: [],
    in_chains: ["chain-ssh-takeover-04"],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "44b0e7a2",
    dimension: "configuration",
    target: "nginx",
    target_label: "nginx",
    icon_key: "nginx",
    identifier: "ssl_protocols",
    observed_value: "TLSv1 TLSv1.1 TLSv1.2",
    expected_value: "TLSv1.2 TLSv1.3",
    score: 7.2,
    severity: "High",
    title: "Deprecated TLS versions accepted",
    impact:
      "TLS 1.0 and 1.1 permit downgrade and padding-oracle attacks against session confidentiality.",
    recommendation: "Set ssl_protocols TLSv1.2 TLSv1.3 and reload nginx.",
    evidence: {
      kind: "config_file",
      location: "/etc/nginx/nginx.conf",
      line: 71,
      snippet: "ssl_protocols TLSv1 TLSv1.1 TLSv1.2;",
    },
    cves: ["CVE-2014-3566"],
    in_chains: [],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "6cf1094b",
    dimension: "configuration",
    target: "nginx",
    target_label: "nginx",
    icon_key: "nginx",
    identifier: "autoindex",
    observed_value: "on",
    expected_value: "off",
    score: 5.6,
    severity: "Medium",
    title: "Directory listing enabled on static locations",
    impact: "Exposes the full file inventory of the document root, including backup artefacts.",
    recommendation: "Set autoindex off in the affected server block.",
    evidence: {
      kind: "config_file",
      location: "/etc/nginx/conf.d/static.conf",
      line: 18,
      snippet: "autoindex on;",
    },
    cves: [],
    in_chains: ["chain-data-exfiltration-01"],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "d3390f18",
    dimension: "exposure",
    target: "postgres",
    target_label: "PostgreSQL",
    icon_key: "postgres",
    identifier: "tcp/0.0.0.0:5432",
    observed_value: "0.0.0.0:5432",
    expected_value: "10.0.0.0/8 only",
    score: 8.1,
    severity: "High",
    title: "PostgreSQL accepts connections from any interface",
    impact:
      "The database is directly reachable, removing the application tier as a control point for access.",
    recommendation: "Set listen_addresses to the private interface and tighten pg_hba.conf.",
    evidence: {
      kind: "listening_socket",
      location: "tcp/0.0.0.0:5432",
      process: "postgres",
      pid: 2210,
    },
    cves: [],
    in_chains: ["chain-data-exfiltration-01"],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "aa17f5c3",
    dimension: "configuration",
    target: "mysql",
    target_label: "MySQL",
    icon_key: "mysql",
    identifier: "skip-grant-tables",
    observed_value: "enabled",
    expected_value: "disabled",
    score: 9.6,
    severity: "Critical",
    title: "MySQL running without the privilege system",
    impact:
      "Any client that reaches the socket has unrestricted administrative access to every schema.",
    recommendation: "Remove skip-grant-tables from my.cnf and restart mysqld.",
    evidence: {
      kind: "config_file",
      location: "/etc/mysql/my.cnf",
      line: 22,
      snippet: "skip-grant-tables",
    },
    cves: [],
    in_chains: ["chain-data-exfiltration-01"],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "e910b2d5",
    dimension: "exposure",
    target: "docker",
    target_label: "Docker",
    icon_key: "docker",
    identifier: "tcp/0.0.0.0:2375",
    observed_value: "unauthenticated daemon socket",
    expected_value: "unix socket only",
    score: 9.2,
    severity: "Critical",
    title: "Docker daemon exposed over unauthenticated TCP",
    impact:
      "Anyone reaching this port can start a privileged container and take over the host filesystem.",
    recommendation: "Disable the TCP listener; use the unix socket or mTLS.",
    evidence: {
      kind: "listening_socket",
      location: "tcp/0.0.0.0:2375",
      process: "dockerd",
      pid: 1187,
    },
    cves: [],
    in_chains: ["chain-container-breakout-05"],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "f2c8a640",
    dimension: "permissions",
    target: "docker",
    target_label: "Docker",
    icon_key: "docker",
    identifier: "/var/run/docker.sock",
    observed_value: "0666 root:docker",
    expected_value: "0660 root:docker",
    score: 8.4,
    severity: "High",
    title: "Docker socket writable by every local user",
    impact: "Local socket access is equivalent to root on the host.",
    recommendation: "Run: chmod 0660 /var/run/docker.sock",
    evidence: {
      kind: "file_metadata",
      location: "/var/run/docker.sock",
      mode: "0666",
      owner: "root",
      group: "docker",
    },
    cves: [],
    in_chains: ["chain-container-breakout-05"],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "0b4d7719",
    dimension: "configuration",
    target: "kubernetes",
    target_label: "Kubernetes",
    icon_key: "kubernetes",
    identifier: "anonymous-auth",
    observed_value: "true",
    expected_value: "false",
    score: 8.9,
    severity: "High",
    title: "API server allows anonymous requests",
    impact: "Unauthenticated callers can enumerate the API surface and any misbound roles.",
    recommendation: "Set --anonymous-auth=false on the API server manifest.",
    evidence: {
      kind: "config_file",
      location: "/etc/kubernetes/manifests/kube-apiserver.yaml",
      line: 27,
      snippet: "- --anonymous-auth=true",
    },
    cves: [],
    in_chains: ["chain-cluster-pivot-06"],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "31e6c8b0",
    dimension: "permissions",
    target: "kubernetes",
    target_label: "Kubernetes",
    icon_key: "kubernetes",
    identifier: "clusterrolebinding:default-sa",
    observed_value: "cluster-admin bound to default SA",
    expected_value: "least-privilege role",
    score: 8.8,
    severity: "High",
    title: "Default service account bound to cluster-admin",
    impact: "Any workload in the namespace inherits full cluster control.",
    recommendation: "Delete the binding and issue scoped roles per workload.",
    evidence: {
      kind: "config_file",
      location: "rbac/clusterrolebinding-default.yaml",
      line: 9,
      snippet: "  name: cluster-admin",
    },
    cves: [],
    in_chains: ["chain-cluster-pivot-06"],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "7a2f3d91",
    dimension: "exposure",
    target: "kubernetes",
    target_label: "Kubernetes",
    icon_key: "kubernetes",
    identifier: "tcp/0.0.0.0:10250",
    observed_value: "kubelet read-write port open",
    expected_value: "control plane only",
    score: 8.3,
    severity: "High",
    title: "Kubelet API reachable outside the control plane",
    impact: "Direct kubelet access allows command execution inside running pods.",
    recommendation: "Restrict 10250/tcp to the control plane subnet.",
    evidence: {
      kind: "listening_socket",
      location: "tcp/0.0.0.0:10250",
      process: "kubelet",
      pid: 3390,
    },
    cves: [],
    in_chains: ["chain-cluster-pivot-06"],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "c5518e07",
    dimension: "configuration",
    target: "tomcat",
    target_label: "Apache Tomcat",
    icon_key: "tomcat",
    identifier: "manager-app",
    observed_value: "deployed with default roles",
    expected_value: "removed in production",
    score: 8.0,
    severity: "High",
    title: "Tomcat manager application deployed in production",
    impact: "Provides a remote deployment endpoint that turns weak credentials into code execution.",
    recommendation: "Remove webapps/manager or restrict it to localhost with a strong realm.",
    evidence: {
      kind: "config_file",
      location: "/opt/tomcat/conf/tomcat-users.xml",
      line: 12,
      snippet: '<role rolename="manager-gui"/>',
    },
    cves: ["CVE-2020-1938"],
    in_chains: [],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "9f04ab6e",
    dimension: "configuration",
    target: "dockerfile",
    target_label: "Dockerfile",
    icon_key: "dockerfile",
    identifier: "USER",
    observed_value: "not set (root)",
    expected_value: "non-root UID",
    score: 6.4,
    severity: "Medium",
    title: "Image runs as root",
    impact: "A container escape starts from uid 0, removing one barrier to host compromise.",
    recommendation: "Add a USER directive with a dedicated non-root UID.",
    evidence: {
      kind: "config_file",
      location: "services/api/Dockerfile",
      line: 19,
      snippet: "CMD [\"node\", \"server.js\"]",
    },
    cves: [],
    in_chains: ["chain-container-breakout-05"],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "3d70f8c2",
    dimension: "configuration",
    target: "azure",
    target_label: "Azure IaC",
    icon_key: "azure",
    identifier: "storageAccount.allowBlobPublicAccess",
    observed_value: "true",
    expected_value: "false",
    score: 7.9,
    severity: "High",
    title: "Storage account allows anonymous blob access",
    impact: "Containers can be made public by any principal with write access to the account.",
    recommendation: "Set allowBlobPublicAccess to false in the Bicep template.",
    evidence: {
      kind: "config_file",
      location: "infra/storage.bicep",
      line: 44,
      snippet: "allowBlobPublicAccess: true",
    },
    cves: [],
    in_chains: [],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "62ba9c15",
    dimension: "permissions",
    target: "nginx",
    target_label: "nginx",
    icon_key: "nginx",
    identifier: "/etc/nginx/ssl/site.key",
    observed_value: "0644 root:root",
    expected_value: "0600 root:root",
    score: 7.1,
    severity: "High",
    title: "TLS private key world-readable",
    impact: "Any local process can copy the private key and impersonate the site.",
    recommendation: "Run: chmod 0600 /etc/nginx/ssl/site.key",
    evidence: {
      kind: "file_metadata",
      location: "/etc/nginx/ssl/site.key",
      mode: "0644",
      owner: "root",
      group: "root",
    },
    cves: [],
    in_chains: [],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "84d1e0af",
    dimension: "exposure",
    target: "mysql",
    target_label: "MySQL",
    icon_key: "mysql",
    identifier: "tcp/0.0.0.0:3306",
    observed_value: "0.0.0.0:3306",
    expected_value: "127.0.0.1",
    score: 8.6,
    severity: "High",
    title: "MySQL bound to every interface",
    impact: "Combined with a disabled grant system, the database is effectively public.",
    recommendation: "Set bind-address = 127.0.0.1 and restart mysqld.",
    evidence: {
      kind: "listening_socket",
      location: "tcp/0.0.0.0:3306",
      process: "mysqld",
      pid: 2611,
    },
    cves: [],
    in_chains: ["chain-data-exfiltration-01"],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
  {
    id: "a0f36b74",
    dimension: "exposure",
    target: "tomcat",
    target_label: "Apache Tomcat",
    icon_key: "tomcat",
    identifier: "tcp/0.0.0.0:8009",
    observed_value: "AJP connector enabled",
    expected_value: "disabled",
    score: 7.0,
    severity: "High",
    title: "AJP connector reachable off-host",
    impact: "AJP trusts its caller, so remote reachability permits request smuggling and file read.",
    recommendation: "Comment out the AJP connector or bind it to 127.0.0.1.",
    evidence: {
      kind: "listening_socket",
      location: "tcp/0.0.0.0:8009",
      process: "java",
      pid: 4102,
    },
    cves: ["CVE-2020-1938"],
    in_chains: [],
    status: "open",
    detected_at: "2026-08-12T14:32:00Z",
  },
];

export const chains: Chain[] = [
  {
    id: "chain-rce-escalation-03",
    title: "Version disclosure on an exposed service enables targeted exploitation",
    score: 9.1,
    severity: "Critical",
    active: true,
    amplification: 1.4,
    exceeds_overall: true,
    cross_dimension: true,
    narrative:
      "Apache discloses its exact version, the service answers on every interface, and the running version has a public RCE. An attacker does not need to fingerprint anything — the banner names the exploit to use, and the port is already open.",
    steps: [
      {
        order: 1,
        finding_id: "7c4e2a1b",
        dimension: "exposure",
        identifier: "tcp/0.0.0.0:80",
        score: 5.2,
        role: "Service reachable from any network",
      },
      {
        order: 2,
        finding_id: "3f2b1c9a",
        dimension: "configuration",
        identifier: "ServerTokens",
        score: 8.5,
        role: "Reveals the exact version to every client",
      },
      {
        order: 3,
        finding_id: "b4e91d70",
        dimension: "permissions",
        identifier: "/var/www:mode",
        score: 6.9,
        role: "Web root writable by the service account, turning code execution into persistence",
      },
    ],
  },
  {
    id: "chain-local-escalation-02",
    title: "World-readable hashes on a host with a permissive sudo policy",
    score: 8.7,
    severity: "High",
    active: true,
    amplification: 1.2,
    exceeds_overall: false,
    cross_dimension: false,
    narrative:
      "Every local account can read the password hashes, and a successful crack lands on an account that can escalate without re-authenticating.",
    steps: [
      {
        order: 1,
        finding_id: "5a8c3b7d",
        dimension: "permissions",
        identifier: "/etc/shadow",
        score: 7.8,
        role: "Hashes readable by any local user",
      },
      {
        order: 2,
        finding_id: "c07a5f31",
        dimension: "permissions",
        identifier: "sudoers:NOPASSWD",
        score: 6.5,
        role: "Cracked account escalates without a password prompt",
      },
    ],
  },
  {
    id: "chain-data-exfiltration-01",
    title: "Unauthenticated data stores reachable from any network",
    score: 9.0,
    severity: "Critical",
    active: true,
    amplification: 1.35,
    exceeds_overall: true,
    cross_dimension: true,
    narrative:
      "Redis answers on every interface with no password, MySQL runs with its privilege system disabled, and a directory listing on the web tier advertises the backup dumps. Reading the dataset requires no credential at any step.",
    steps: [
      {
        order: 1,
        finding_id: "6cf1094b",
        dimension: "configuration",
        identifier: "autoindex",
        score: 5.6,
        role: "Advertises backup artefacts and internal paths",
      },
      {
        order: 2,
        finding_id: "9d1f4e2c",
        dimension: "exposure",
        identifier: "tcp/0.0.0.0:6379",
        score: 9.4,
        role: "Key-value store readable and writable without authentication",
      },
      {
        order: 3,
        finding_id: "aa17f5c3",
        dimension: "configuration",
        identifier: "skip-grant-tables",
        score: 9.6,
        role: "Relational store accepts any client as an administrator",
      },
      {
        order: 4,
        finding_id: "84d1e0af",
        dimension: "exposure",
        identifier: "tcp/0.0.0.0:3306",
        score: 8.6,
        role: "That administrative surface is reachable off-host",
      },
    ],
  },
  {
    id: "chain-ssh-takeover-04",
    title: "Internet-facing SSH accepting root logins with passwords",
    score: 9.5,
    severity: "Critical",
    active: true,
    amplification: 1.3,
    exceeds_overall: true,
    cross_dimension: true,
    narrative:
      "The administrative service is reachable from any source address, accepts passwords, and permits the root account directly. A single guessed credential is a full host compromise with no intermediate step.",
    steps: [
      {
        order: 1,
        finding_id: "88ac21fd",
        dimension: "exposure",
        identifier: "tcp/0.0.0.0:22",
        score: 7.6,
        role: "Administrative service reachable from the internet",
      },
      {
        order: 2,
        finding_id: "2b77c0e9",
        dimension: "configuration",
        identifier: "PasswordAuthentication",
        score: 6.8,
        role: "Guessable secret accepted as proof of identity",
      },
      {
        order: 3,
        finding_id: "1e5d8a44",
        dimension: "configuration",
        identifier: "PermitRootLogin",
        score: 9.1,
        role: "The guessed account is root — no escalation needed",
      },
    ],
  },
  {
    id: "chain-container-breakout-05",
    title: "Root containers on a host with an open Docker control plane",
    score: 8.9,
    severity: "High",
    active: true,
    amplification: 1.25,
    exceeds_overall: true,
    cross_dimension: true,
    narrative:
      "The image runs as uid 0, the daemon socket is world-writable locally, and the daemon also answers unauthenticated on TCP. Any of the three alone is bad practice; together they collapse the boundary between container and host.",
    steps: [
      {
        order: 1,
        finding_id: "9f04ab6e",
        dimension: "configuration",
        identifier: "USER",
        score: 6.4,
        role: "Workload starts as uid 0 inside the container",
      },
      {
        order: 2,
        finding_id: "f2c8a640",
        dimension: "permissions",
        identifier: "/var/run/docker.sock",
        score: 8.4,
        role: "Local socket access equals root on the host",
      },
      {
        order: 3,
        finding_id: "e910b2d5",
        dimension: "exposure",
        identifier: "tcp/0.0.0.0:2375",
        score: 9.2,
        role: "The same control plane is reachable remotely without authentication",
      },
    ],
  },
  {
    id: "chain-cluster-pivot-06",
    title: "Anonymous API access to a cluster with an over-privileged default account",
    score: 9.3,
    severity: "Critical",
    active: true,
    amplification: 1.45,
    exceeds_overall: true,
    cross_dimension: true,
    narrative:
      "The API server answers anonymous callers, the default service account carries cluster-admin, and the kubelet accepts commands from outside the control plane. Enumeration, privilege and execution are each available separately.",
    steps: [
      {
        order: 1,
        finding_id: "0b4d7719",
        dimension: "configuration",
        identifier: "anonymous-auth",
        score: 8.9,
        role: "API surface enumerable without credentials",
      },
      {
        order: 2,
        finding_id: "31e6c8b0",
        dimension: "permissions",
        identifier: "clusterrolebinding:default-sa",
        score: 8.8,
        role: "Any workload token is effectively cluster-admin",
      },
      {
        order: 3,
        finding_id: "7a2f3d91",
        dimension: "exposure",
        identifier: "tcp/0.0.0.0:10250",
        score: 8.3,
        role: "Kubelet executes commands in pods from off-cluster",
      },
    ],
  },
];

export const targets: Target[] = [
  {
    id: "apache-httpd",
    label: "Apache HTTPD",
    icon_key: "apache",
    version: "2.4.58",
    score: 8.5,
    severity: "High",
    findings_count: 12,
    critical_count: 1,
    benchmark: "CIS Apache HTTP Server 2.4 v2.1",
    status: "online",
    sparkline: [7.9, 8.1, 8.4, 8.2, 8.6, 8.5, 8.5],
  },
  {
    id: "nginx",
    label: "nginx",
    icon_key: "nginx",
    version: "1.25.3",
    score: 7.2,
    severity: "High",
    findings_count: 7,
    critical_count: 0,
    benchmark: "CIS NGINX v2.1",
    status: "online",
    sparkline: [6.5, 6.8, 7.0, 7.1, 7.0, 7.2, 7.2],
  },
  {
    id: "openssh",
    label: "SSH",
    icon_key: "ssh",
    version: "OpenSSH 9.6p1",
    score: 9.1,
    severity: "Critical",
    findings_count: 5,
    critical_count: 1,
    benchmark: "CIS Distribution Independent Linux v2.0",
    status: "online",
    sparkline: [8.4, 8.6, 8.9, 9.0, 9.1, 9.1, 9.1],
  },
  {
    id: "redis",
    label: "Redis",
    icon_key: "redis",
    version: "7.2.4",
    score: 9.4,
    severity: "Critical",
    findings_count: 3,
    critical_count: 1,
    benchmark: "CIS Redis v1.1",
    status: "online",
    sparkline: [5.1, 5.2, 6.7, 8.9, 9.4, 9.4, 9.4],
  },
  {
    id: "postgres",
    label: "PostgreSQL",
    icon_key: "postgres",
    version: "15.6",
    score: 6.4,
    severity: "Medium",
    findings_count: 4,
    critical_count: 0,
    benchmark: "CIS PostgreSQL 15 v1.1",
    status: "online",
    sparkline: [6.6, 6.5, 6.4, 6.4, 6.5, 6.4, 6.4],
  },
  {
    id: "mysql",
    label: "MySQL",
    icon_key: "mysql",
    version: "8.0.36",
    score: 9.6,
    severity: "Critical",
    findings_count: 6,
    critical_count: 1,
    benchmark: "CIS MySQL 8.0 v1.3",
    status: "online",
    sparkline: [9.0, 9.2, 9.4, 9.6, 9.6, 9.6, 9.6],
  },
  {
    id: "docker",
    label: "Docker",
    icon_key: "docker",
    version: "25.0.3",
    score: 9.2,
    severity: "Critical",
    findings_count: 5,
    critical_count: 1,
    benchmark: "CIS Docker v1.6",
    status: "online",
    sparkline: [8.4, 8.6, 8.8, 9.0, 9.2, 9.2, 9.2],
  },
  {
    id: "dockerfile",
    label: "Dockerfile",
    icon_key: "dockerfile",
    version: "services/api",
    score: 6.4,
    severity: "Medium",
    findings_count: 3,
    critical_count: 0,
    benchmark: "CIS Docker Benchmark v1.6 — Dockerfile ruleset",
    status: "offline",
    sparkline: [6.9, 6.8, 6.6, 6.4, 6.4, 6.4, 6.4],
  },
  {
    id: "kubernetes",
    label: "Kubernetes",
    icon_key: "kubernetes",
    version: "1.30",
    score: 8.9,
    severity: "High",
    findings_count: 9,
    critical_count: 0,
    benchmark: "CIS Kubernetes v1.9",
    status: "online",
    sparkline: [8.1, 8.3, 8.5, 8.7, 8.8, 8.9, 8.9],
  },
  {
    id: "ubuntu",
    label: "Ubuntu",
    icon_key: "ubuntu",
    version: "22.04 LTS",
    score: 7.8,
    severity: "High",
    findings_count: 6,
    critical_count: 0,
    benchmark: "CIS Ubuntu Linux 22.04 v2.0",
    status: "online",
    sparkline: [7.4, 7.6, 7.6, 7.8, 7.8, 7.8, 7.8],
  },
  {
    id: "tomcat",
    label: "Apache Tomcat",
    icon_key: "tomcat",
    version: "10.1.19",
    score: 8.0,
    severity: "High",
    findings_count: 4,
    critical_count: 0,
    benchmark: "CIS Apache Tomcat 10 v1.1",
    status: "online",
    sparkline: [7.2, 7.5, 7.8, 7.9, 8.0, 8.0, 8.0],
  },
  {
    id: "azure",
    label: "Azure IaC",
    icon_key: "azure",
    version: "Bicep infra/",
    score: 7.9,
    severity: "High",
    findings_count: 5,
    critical_count: 0,
    benchmark: "CIS Microsoft Azure Foundations v2.1",
    status: "offline",
    sparkline: [7.1, 7.3, 7.6, 7.7, 7.9, 7.9, 7.9],
  },
];

export const watchSessions: WatchSession[] = [
  {
    id: "w-01",
    target: "apache-httpd",
    target_label: "Apache HTTPD",
    icon_key: "apache",
    state: "live",
    interval: "every 5 min",
    last_event_at: "2026-08-12T14:29:00Z",
    score: 8.5,
    severity: "High",
    sparkline: [8.1, 8.2, 8.4, 8.3, 8.5, 8.5, 8.5],
  },
  {
    id: "w-02",
    target: "redis",
    target_label: "Redis",
    icon_key: "redis",
    state: "live",
    interval: "every 1 min",
    last_event_at: "2026-08-12T14:31:00Z",
    score: 9.4,
    severity: "Critical",
    sparkline: [5.2, 5.2, 6.8, 9.4, 9.4, 9.4, 9.4],
  },
  {
    id: "w-03",
    target: "kubernetes",
    target_label: "Kubernetes",
    icon_key: "kubernetes",
    state: "live",
    interval: "every 15 min",
    last_event_at: "2026-08-12T14:18:00Z",
    score: 8.9,
    severity: "High",
    sparkline: [8.5, 8.6, 8.7, 8.8, 8.9, 8.9, 8.9],
  },
  {
    id: "w-04",
    target: "postgres",
    target_label: "PostgreSQL",
    icon_key: "postgres",
    state: "stale",
    interval: "every 10 min",
    last_event_at: "2026-08-12T09:04:00Z",
    score: 6.4,
    severity: "Medium",
    sparkline: [6.4, 6.4, 6.5, 6.4, 6.4, 6.4, 6.4],
  },
  {
    id: "w-05",
    target: "openssh",
    target_label: "SSH",
    icon_key: "ssh",
    state: "paused",
    interval: "manual",
    last_event_at: "2026-08-11T20:12:00Z",
    score: 9.1,
    severity: "Critical",
    sparkline: [9.1, 9.1, 9.1, 9.1, 9.1, 9.1, 9.1],
  },
];

export const watchEvents: WatchEvent[] = [
  {
    id: "e-1",
    at: "2026-08-12T14:31:00Z",
    target_label: "Redis",
    icon_key: "redis",
    kind: "new_finding",
    message: "bind directive removed from redis.conf — listener moved to 0.0.0.0:6379",
    delta: 4.2,
  },
  {
    id: "e-2",
    at: "2026-08-12T14:29:00Z",
    target_label: "Apache HTTPD",
    icon_key: "apache",
    kind: "reassessment",
    message: "apache2.conf changed — 41 rules re-evaluated",
    delta: 0.0,
  },
  {
    id: "e-3",
    at: "2026-08-12T13:58:00Z",
    target_label: "nginx",
    icon_key: "nginx",
    kind: "resolved",
    message: "server_tokens set to off — finding closed",
    delta: -0.6,
  },
  {
    id: "e-4",
    at: "2026-08-12T13:20:00Z",
    target_label: "Kubernetes",
    icon_key: "kubernetes",
    kind: "config_change",
    message: "kube-apiserver manifest edited on node cp-01",
    delta: null,
  },
  {
    id: "e-5",
    at: "2026-08-12T12:44:00Z",
    target_label: "Docker",
    icon_key: "docker",
    kind: "new_finding",
    message: "daemon.json now exposes tcp://0.0.0.0:2375",
    delta: 2.8,
  },
  {
    id: "e-6",
    at: "2026-08-12T11:02:00Z",
    target_label: "Ubuntu",
    icon_key: "ubuntu",
    kind: "reassessment",
    message: "scheduled sweep completed — 96 rules evaluated",
    delta: 0.0,
  },
];

export const activity = [
  { id: "a1", at: "2026-08-12T14:32:00Z", text: "Assessment #4821 completed across 12 targets", kind: "scan" },
  { id: "a2", at: "2026-08-12T14:31:00Z", text: "New critical finding on Redis — tcp/0.0.0.0:6379", kind: "finding" },
  { id: "a3", at: "2026-08-12T14:20:00Z", text: "Attack chain chain-cluster-pivot-06 became active", kind: "chain" },
  { id: "a4", at: "2026-08-12T13:58:00Z", text: "nginx server_tokens finding resolved", kind: "resolved" },
  { id: "a5", at: "2026-08-12T09:15:00Z", text: "Knowledge base updated to sha256 f595efe56da0 (514 rules)", kind: "kb" },
];

export const portTable = [
  { port: "22/tcp", service: "sshd", target_label: "SSH", icon_key: "ssh", bind: "0.0.0.0", reachable: true, score: 7.6, severity: "High" as const },
  { port: "80/tcp", service: "apache2", target_label: "Apache HTTPD", icon_key: "apache", bind: "0.0.0.0", reachable: true, score: 5.2, severity: "Medium" as const },
  { port: "443/tcp", service: "nginx", target_label: "nginx", icon_key: "nginx", bind: "0.0.0.0", reachable: true, score: 3.1, severity: "Low" as const },
  { port: "2375/tcp", service: "dockerd", target_label: "Docker", icon_key: "docker", bind: "0.0.0.0", reachable: true, score: 9.2, severity: "Critical" as const },
  { port: "3306/tcp", service: "mysqld", target_label: "MySQL", icon_key: "mysql", bind: "0.0.0.0", reachable: true, score: 8.6, severity: "High" as const },
  { port: "5432/tcp", service: "postgres", target_label: "PostgreSQL", icon_key: "postgres", bind: "0.0.0.0", reachable: true, score: 8.1, severity: "High" as const },
  { port: "6379/tcp", service: "redis-server", target_label: "Redis", icon_key: "redis", bind: "0.0.0.0", reachable: true, score: 9.4, severity: "Critical" as const },
  { port: "8009/tcp", service: "java", target_label: "Apache Tomcat", icon_key: "tomcat", bind: "0.0.0.0", reachable: true, score: 7.0, severity: "High" as const },
  { port: "10250/tcp", service: "kubelet", target_label: "Kubernetes", icon_key: "kubernetes", bind: "0.0.0.0", reachable: true, score: 8.3, severity: "High" as const },
  { port: "5000/tcp", service: "registry", target_label: "Docker", icon_key: "docker", bind: "127.0.0.1", reachable: false, score: 0.0, severity: "None" as const },
];

export const findingById = (id: string) => findings.find((f) => f.id === id);
export const chainById = (id: string) => chains.find((c) => c.id === id);
export const dimensionById = (id: string) => posture.dimensions.find((d) => d.id === id);
export const findingsByDimension = (id: string) => findings.filter((f) => f.dimension === id);
