/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as BuildRouteImport } from './routes/build'
import { Route as ChainsRouteImport } from './routes/chains'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TargetsRouteImport } from './routes/targets'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as DimensionsIndexRouteImport } from './routes/dimensions.index'
import { Route as DimensionsDimensionIdRouteImport } from './routes/dimensions.$dimensionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainsRoute = ChainsRouteImport.update({
  id: '/chains',
  path: '/chains',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsRoute = TargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const DimensionsIndexRoute = DimensionsIndexRouteImport.update({
  id: '/dimensions/',
  path: '/dimensions/',
  getParentRoute: () => rootRouteImport,
} as any)
const DimensionsDimensionIdRoute = DimensionsDimensionIdRouteImport.update({
  id: '/dimensions/$dimensionId',
  path: '/dimensions/$dimensionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/build': typeof BuildRoute
  '/chains': typeof ChainsRoute
  '/findings': typeof FindingsRoute
  '/knowledge': typeof KnowledgeRoute
  '/plugins': typeof PluginsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/targets': typeof TargetsRoute
  '/watch': typeof WatchRoute
  '/dimensions/$dimensionId': typeof DimensionsDimensionIdRoute
  '/dimensions/': typeof DimensionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/build': typeof BuildRoute
  '/chains': typeof ChainsRoute
  '/findings': typeof FindingsRoute
  '/knowledge': typeof KnowledgeRoute
  '/plugins': typeof PluginsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/targets': typeof TargetsRoute
  '/watch': typeof WatchRoute
  '/dimensions/$dimensionId': typeof DimensionsDimensionIdRoute
  '/dimensions': typeof DimensionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/build': typeof BuildRoute
  '/chains': typeof ChainsRoute
  '/findings': typeof FindingsRoute
  '/knowledge': typeof KnowledgeRoute
  '/plugins': typeof PluginsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/targets': typeof TargetsRoute
  '/watch': typeof WatchRoute
  '/dimensions/$dimensionId': typeof DimensionsDimensionIdRoute
  '/dimensions/': typeof DimensionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/build'
    | '/chains'
    | '/findings'
    | '/knowledge'
    | '/plugins'
    | '/reports'
    | '/settings'
    | '/targets'
    | '/watch'
    | '/dimensions/$dimensionId'
    | '/dimensions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/build'
    | '/chains'
    | '/findings'
    | '/knowledge'
    | '/plugins'
    | '/reports'
    | '/settings'
    | '/targets'
    | '/watch'
    | '/dimensions/$dimensionId'
    | '/dimensions'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/build'
    | '/chains'
    | '/findings'
    | '/knowledge'
    | '/plugins'
    | '/reports'
    | '/settings'
    | '/targets'
    | '/watch'
    | '/dimensions/$dimensionId'
    | '/dimensions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  BuildRoute: typeof BuildRoute
  ChainsRoute: typeof ChainsRoute
  FindingsRoute: typeof FindingsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  PluginsRoute: typeof PluginsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TargetsRoute: typeof TargetsRoute
  WatchRoute: typeof WatchRoute
  DimensionsDimensionIdRoute: typeof DimensionsDimensionIdRoute
  DimensionsIndexRoute: typeof DimensionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chains': {
      id: '/chains'
      path: '/chains'
      fullPath: '/chains'
      preLoaderRoute: typeof ChainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets': {
      id: '/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof TargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dimensions/': {
      id: '/dimensions/'
      path: '/dimensions'
      fullPath: '/dimensions/'
      preLoaderRoute: typeof DimensionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dimensions/$dimensionId': {
      id: '/dimensions/$dimensionId'
      path: '/dimensions/$dimensionId'
      fullPath: '/dimensions/$dimensionId'
      preLoaderRoute: typeof DimensionsDimensionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  BuildRoute: BuildRoute,
  ChainsRoute: ChainsRoute,
  FindingsRoute: FindingsRoute,
  KnowledgeRoute: KnowledgeRoute,
  PluginsRoute: PluginsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TargetsRoute: TargetsRoute,
  WatchRoute: WatchRoute,
  DimensionsDimensionIdRoute: DimensionsDimensionIdRoute,
  DimensionsIndexRoute: DimensionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
